[lib]
proc-macro = true

[package]
name = "conseq"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Macro to conditionally repeat a piece of code in a sequence."
repository = "https://github.com/pstroka/conseq"

[dependencies]
